Support for Haml 6.x
leshill/handlebars_assets pull request #180
Opened 2023-12-07 22:23 UTC by braindeaf

Added support for Haml 6.x. It really boils down to the 6.x change

```
Haml::Engine.new(str, options)
# ->
Haml::Template.new(options) { str }
```

2023-12-07 23:00 UTC, AlexRiedler commented on handlebars_assets.gemspec
> +  s.add_development_dependency "haml", ">= 4.0"
probably want to put upperbound on this

2023-12-07 23:01 UTC, AlexRiedler requested changes
minor change; and then it should be good to go. I haven't had much transaction on working on Ruby in a long time, but will happily release if things look good on this end.

2024-12-15 22:44 UTC, AlexRiedler approved these changes

2024-12-15 22:44 UTC, merged

2024-12-16 00:24 UTC, braindeaf commented
Thank you kindly :)